### ISSUE TITLE
Problem with create page

### ISSUE THREAD

**Issue by hnahoulder** [Arello-Mobile/confluence-publisher#3]
Hello, I am trying to use your package confluence-publisher. But I have some problems
When I want to create a new page I got nothing?
May be, I don't know how to right the config file:

In my config file I wrote: 
version: 2
url: http://appsiege.xxxxxx.fr:97/confluence/
base_dir: /build/json

but on the section page, I don't know how to right it because I just have the number of my parent page and I want to create the others pages.

Can you help me please?

Thank you

**Comment by ikeeip** [comment]
Hi there! You can do it by using `conf_page_maker` from this package. Run it with `--parent-id` option, like this: `conf_page_maker --parent-id 49807774 --auth AUTHINFORMATION test.yml`. 

In config file you should not set any ids for pages that does not esists. Just set only a `title` field for this pages. There is an example:

```
version: 2
url: https://confluence.atlassian.com
pages:
- title: child page 1
- title: child page 2
- title: child page 3
- id: 58622641
  title: exists child page
```

The `conf_page_maker` will create empty pages with titles and also update ids in config file.  There is a  updated config file:

```
version: 2
url: https://confluence.atlassian.com
pages:
- id: 58622642
  title: child page 1
- id: 58622643
  title: child page 2
- id: 58622644
  title: child page 3
- id: 58622641
  title: exists child page
```

P.S. While testing this example I found a bug in embedded pages. Will fix it soon.
